### ISSUE TITLE
New article: How to Choose Variable Names in ML Projects

### ISSUE THREAD

**Issue by ruzarx** [DataTalksClub/datatalksclub.github.io#10]
**Title**: How to Choose Variable Names in ML Projects
**Google doc**: https://docs.google.com/document/d/1DOxgdPz5VJOew_6BDHHTES_w_75infxSJ1b1J0Ep74w/edit?usp=sharing
**Profile**: igordemidov
**Tags**: machine-learning,python,clean-code

**Comment by alexeygrigorev** [comment]
There are a few pending comments, once you resolve everything, please let me know and we'll publish it

**Comment by alexeygrigorev** [comment]
Published: https://datatalks.club/blog/naming-variables-in-machine-learning.html

Thank you for your contribution!

There's still one thing though. We need attribution in one of the images to make sure that we can use the image in the article. If it's your image, you can say "(image by the author)".  Once it's done, we'll announce the article

Please let us know the source here in the comments and we'll add them to the article (or create a PR [here](https://github.com/DataTalksClub/datatalksclub.github.io/blob/main/_posts/2022-10-02-naming-variables-in-machine-learning.md?plain=1#L109))

**Comment by alexeygrigorev** [comment]
If you'd like, you can change your bio by creating a PR to [this file](https://github.com/DataTalksClub/datatalksclub.github.io/blob/main/_people/igordemidov.md?plain=1#L11)

**Comment by alexeygrigorev** [comment]
@ruzarx can you please take a look at it?

**Comment by ruzarx** [comment]
![name_1](https://user-images.githubusercontent.com/34417502/197341837-5f84a1be-e892-4f5c-92b3-5621bde53cfb.jpg)
![name_2](https://user-images.githubusercontent.com/34417502/197341843-73ba78ef-43e5-4ba5-b950-63e380b18bac.jpg)

I had to change both images. The first one I made myself, the second one I took from open source. Images need to changed to the ones above. Attributions I have added via [PR](https://github.com/DataTalksClub/datatalksclub.github.io/pull/14)

**Comment by alexeygrigorev** [comment]
Thanks Igor!
