### ISSUE TITLE
New article: Do You Know the Golden Rules While Working With Data?

### ISSUE THREAD

**Issue by guoliveira** [DataTalksClub/datatalksclub.github.io#11]
**Title**: Do You Know the Golden Rules While Working With Data?
**Google doc**: https://docs.google.com/document/d/1LAyWJf5Yr5bui7x1ECMDIFmm7HKjAmTSFTPbvl0SQNU/edit#heading=h.dvo5mifoxtwy
**Profile**: https://datatalks.club/people/luisoliveira.html
**Tags**: data, data engineering, data science, best practices

**Comment by alexeygrigorev** [comment]
just a few minor suggestions - apart from that, it's good to go!

**Comment by guoliveira** [comment]
Done with your suggestions :) Thank you for your review

**Comment by alexeygrigorev** [comment]
https://datatalks.club/blog/do-you-know-golden-rules-while-working-with-data.html published 

@amitfrancis please announce the article

**Comment by amitfrancis** [comment]
I just scheduled the article on our social media platforms :)
