### ISSUE TITLE
New article: Important SQL Fact That Everyone Should Know

### ISSUE THREAD

**Issue by guoliveira** [DataTalksClub/datatalksclub.github.io#12]
**Title**: Important SQL Fact That Everyone Should Know
**Google doc**: https://docs.google.com/document/d/12KhMupXkzXPDP5i1C2EiKvlpE4bk5XHgLTd8Ohx_udQ/edit?usp=sharing 
**Profile**: https://datatalks.club/people/luisoliveira.html
**Tags**: SQL, Data Engineering

**Comment by alexeygrigorev** [comment]
Published it. Can you please format SQL queries with your favourite formatter? 

https://github.com/DataTalksClub/datatalksclub.github.io/blob/main/_posts/2022-10-21-important-sql-fact-that-everyone-should-know.md?plain=1#L80

And then create a PR here please with all the queries formatted 

(By the way, the article is already available here: https://datatalks.club/blog/important-sql-fact-that-everyone-should-know.html)

**Comment by alexeygrigorev** [comment]
Thank you!
