### ISSUE TITLE
New article: Guidelines to Get a Data Engineer Job Against the Odds 

### ISSUE THREAD

**Issue by guoliveira** [DataTalksClub/datatalksclub.github.io#15]
**Title**: Guidelines to Get a Data Engineer Job Against the Odds 
**Google doc**: https://docs.google.com/document/d/1HOTY-M4wLI7s_qkMn3yg7TADod1xTSfnor5iX-a8IRw/edit?usp=sharing
**Profile**: https://datatalks.club/people/luisoliveira.html
**Tags**: Career, Data Engineer, Advice

**Comment by alexeygrigorev** [comment]
Published it, thank you! 

https://datatalks.club/blog/guidelines-to-get-data-engineer-job-against-odds.html

@amitfrancis please announce it
