### ISSUE TITLE
New article: How to run PostgreSQL and PgAdmin with Docker 

### ISSUE THREAD

**Issue by guoliveira** [DataTalksClub/datatalksclub.github.io#16]
**Title**: How to run PostgreSQL and PgAdmin with Docker
**Google doc**: (https://docs.google.com/document/d/1DrPJaoGG55fqZcu_tU3yRIzgdqVpZd1tSWWMkyEwtH8/edit#)
**Profile**: [ Luís Oliveira](https://datatalks.club/people/luisoliveira.html)
**Tags**: PostgreSQL, pgAdmin, Docker, Data Engineering

**Comment by alexeygrigorev** [comment]
Published: https://datatalks.club/blog/how-to-run-postgresql-and-pgadmin-with-docker.html
Thank you!
