### ISSUE TITLE
Idea: include a page on the website for the courses

### ISSUE THREAD

**Issue by rosonaeldred** [DataTalksClub/datatalksclub.github.io#6]
Could you add a webpage page linking to the courses? 
I thought they used to appear under events, but they are really separate things.
This would also help for e.g. the mlbookcamp repository, which is under alexey's github instead of the DTC account.

**Comment by alexeygrigorev** [comment]
![image](https://user-images.githubusercontent.com/875246/175786602-fa404367-a1d7-4447-81dc-f439c0beb8e1.png)

Sneak peak into our new website =)

**Comment by alexeygrigorev** [comment]
The development of the new website happens here - https://github.com/DataTalksClub/website-django
So you can watch it if you're interested (it will probably take some time before it's up and running though)

**Comment by alexeygrigorev** [comment]
So the new website never happened but we have this 

https://datatalks.club/blog/guide-to-free-online-courses-at-datatalks-club.html
