### ISSUE TITLE
New article: How to Setup a Lightweight Local Version for Airflow

### ISSUE THREAD

**Issue by guoliveira** [DataTalksClub/datatalksclub.github.io#8]
**Title**: How to Setup a Lightweight Local Version for Airflow
**Google doc**: https://docs.google.com/document/d/1VYYoWvLgDqRt7EBgoEHvCOQgD5vRpN_gbFYfncv6jpc/edit?usp=sharing
**Profile**: https://datatalks.club/people/luisoliveira.html
**Tags**: Airflow , Docker, data-engineering

**Comment by alexeygrigorev** [comment]
Post is published: https://datatalks.club/blog/how-to-setup-lightweight-local-version-for-airflow.html

Thank you for your contribution!
