### ISSUE TITLE
New article: Regularization in regression

### ISSUE THREAD

**Issue by Ksyula** [DataTalksClub/datatalksclub.github.io#9]
**Title**: <Name of the article>
**Google doc**: [Url of the google doc](https://docs.google.com/document/d/1tpbVhKxXF465p6B8lse5nKnRJ7vgn_41lp5tdDNFs6w/edit#heading=h.qmylcoh3x07r) 
**Profile**: ksenia.legostay
**Tags**: linearregression, regularization

**Comment by alexeygrigorev** [comment]
Francis, please announce the article

**Comment by amitfrancis** [comment]
Done! Scheduled for 5:00 PM CET
